//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDanceManageApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonements
    {
        public int id_ab { get; set; }
        public string kind_ab { get; set; }
        public Nullable<int> kind_numbers_in_ab { get; set; }
        public Nullable<int> numbers_lessons_ab { get; set; }
        public Nullable<int> id_client { get; set; }
    
        public virtual clientinformation clientinformation { get; set; }
    }
}
