//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDanceManageApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDanceEntities : DbContext
    {
        public SchoolDanceEntities()
            : base("name=SchoolDanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abonements> abonements { get; set; }
        public virtual DbSet<clientinformation> clientinformation { get; set; }
        public virtual DbSet<dancedirection> dancedirection { get; set; }
        public virtual DbSet<grouponetraining_client> grouponetraining_client { get; set; }
        public virtual DbSet<individ_one_trainig> individ_one_trainig { get; set; }
        public virtual DbSet<probnoe_group> probnoe_group { get; set; }
        public virtual DbSet<probnoe_individ> probnoe_individ { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<timetable> timetable { get; set; }
    }
}
