//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string nameSender { get; set; }
        public string emailSender { get; set; }
        public string wish { get; set; }
    }
}
