//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDanceManageApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class probnoe_group
    {
        public int id_prob_gr { get; set; }
        public string visits_gr { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_dance { get; set; }
    
        public virtual clientinformation clientinformation { get; set; }
        public virtual dancedirection dancedirection { get; set; }
    }
}
