//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDanceManageApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public System.DateTime data { get; set; }
        public Nullable<int> id_dance { get; set; }
    
        public virtual dancedirection dancedirection { get; set; }
    }
}
